services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/cache:/var/cache/nginx
    restart: always
    depends_on:
      - mongo
    networks:
      - app-network

  flask:
    build:
      context: .
    ports:
      - "5000:5000"
    expose:
      - "5000"
    env_file:
      - .env
    # environment:
    #   - FLASK_APP=app.py
    #   - FLASK_ENV=production
    #   - MONGO_URI=mongodb://mongo:27017/auth_db
    #   - SECRET_KEY=minha_secreta
    volumes:
      - .:/app
    restart: always
    networks:
      - app-network
    depends_on:
      - mongo

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
